### ISSUE TITLE
trying to figure out how to run scrip

### ISSUE THREAD

**Issue by lednevandrey04** [Inventsable/getPixelColor#1]
Hi Inventsable.

I'm trying to figure out how to run your script using Visual Studio Code

Placed getPixelColor.js in the working directory, uncommented the last lines of the code, rewrote the save path
"C:/Users/TRSch/OneDrive/Documents/Adobe Scripts/ILST - GetRGBFromBMP/sandbox/result.json"
to the directory where the script is located,
"E:/Progs/adobe/Scripts/Ill/result.json"

After starting ( F5 ) the program hangs. ???

**Comment by Inventsable** [comment]
It can be dependent on whatever mechanism is actually running the script, e.g. ESTK or similar Adobe Script Runner extension. Can you verify by running the script via File > Scripts > Other Scripts? Might also help to have the exact same file you're using in order to replicate whatever issue is being had.

**Comment by Inventsable** [comment]
Also of note, JSON is not included in my script. It's assumed that you'd be using a [JSON polyfill ](https://github.com/sam272/json3forillustrator) since the script would only need this for the logging itself, not for the base function. You could replace this with a rudimentary check:

```js
getPixelColor([0, 1], {
  onComplete: function (result) {
    alert(result);
  },
});
```

**Comment by Inventsable** [comment]
I've updated the script and have ran it via File > Scripts > Other Scripts to verify the below:

```js
getPixelColor([[0, 1]], {
  onAfterParse: function (result) {
    alert(result); // [Object object]
  },
  onComplete: function (result) {
    alert(result.r); // 53
  },
});
```

**Comment by lednevandrey04** [comment]
Downloaded the latest version of the getPixelColor file, does this version have the last lines commented out?
Downloaded JSON3 package. I don't have it installed. How to install it?

**Comment by Inventsable** [comment]
The latest does not have the lines from above, you'd need to paste them in at the bottom or use #include from another file and use them there. You can do the same for JSON where you #include it from your own file or paste it at the top, though it isn't required for the script to actually run.

**Comment by lednevandrey04** [comment]
when I connect an external script I use something like this line
//@include "E:/Progs/adobe/Scripts/PS/f_savePSDFile.jsx"

In the case of JSON3, there is a json3forillustrator-master directory

Which file should be imported from it?

**Comment by lednevandrey04** [comment]
I inclide json3.js in body your script. (JSON polyfill](https://github.com/sam272/json3forillustrator))
After start execution, i see message: Uncaught JavaScript exeption: Error Line 589 Column 1.
Try use script on big picture (463x373 pixels)

**Comment by lednevandrey04** [comment]
Error in json3.js
